# Generated by Django 5.1.15 on 2026-01-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oroshine_webapp', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='welcome_email_sent',
        ),
    ]
