# Generated by Django 5.1.15 on 2026-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oroshine_webapp', '0003_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
